### ISSUE TITLE
error: C2276: “&”: 绑定成员函数表达式上的非法操作

### ISSUE THREAD

**Issue by RedHaohao** [TheThreeDog/PictureMatching#1]
下载了作者的程序，但是运行时有这个问题，自己查了好久没有解决。
#define my_selector(_SELECTOR) (FUNC_PTR)(&_SELECTOR)
void TDAbstractButton::setCallback(QObject *obj, FUNC_PTR func)
我觉得是&_SELECTOR 有问题。
请大神帮助一下。

**Comment by TheThreeDog** [comment]
这个问题我之前也遇到过，由于我这里用的Qt  Mingw的编译器， 这个写法在VS的编译器下貌似是不支持的， 后续我会找到更加兼容的写法来实现，如果方便的话，请将此程序拿到QtCreator下编译运行。

**Comment by RedHaohao** [comment]
我用的就是qt creator 但是我看了发现没有mingw 编译器。下载mingw完，配置 构建套件时出现 the compiler XXXX can not produce code for the qt versionXXX的问题。
我准备再下载对应版本的qt。

**Comment by TheThreeDog** [comment]
嗯，你直接装带QtCreator的Qt，比较方便。我开发环境使用的是Qt5.7。

**Comment by RedHaohao** [comment]
谢谢

**Comment by TheThreeDog** [comment]
> 下载了作者的程序，但是运行时有这个问题，自己查了好久没有解决。
> #define my_selector(_SELECTOR) (FUNC_PTR)(&_SELECTOR)
> void TDAbstractButton::setCallback(QObject *obj, FUNC_PTR func)
> 我觉得是&_SELECTOR 有问题。
> 请大神帮助一下。


原谅我这才疏学浅，之前的编译不是编译器的问题，而是我写法的问题。
最近重新梳理函数指针的知识才知道我那会儿能编译过只是正好MinGW的gcc对我网开一面而已。
这份代码换了平台和编译器都拉垮了。

现在问题已经解决。回头有空可以再用VC那套编译器再试试。
